// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkad98agMca5bDmmCAuWJ_G9Sl34er4fI',
    appId: '1:522810314595:web:ae37f50d2690ab596d4d56',
    messagingSenderId: '522810314595',
    projectId: 'notificationappflutter-3337c',
    authDomain: 'notificationappflutter-3337c.firebaseapp.com',
    storageBucket: 'notificationappflutter-3337c.firebasestorage.app',
    measurementId: 'G-081N1J0VJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_3xt1jTlAg_-OfuTJ3VTZRLWA5mrphYE',
    appId: '1:522810314595:android:f6eb6c1745ac6b436d4d56',
    messagingSenderId: '522810314595',
    projectId: 'notificationappflutter-3337c',
    storageBucket: 'notificationappflutter-3337c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYpziocAYQw_bexzG-YDK7IHW_V9rwz4',
    appId: '1:522810314595:ios:8367d4523d0450106d4d56',
    messagingSenderId: '522810314595',
    projectId: 'notificationappflutter-3337c',
    storageBucket: 'notificationappflutter-3337c.firebasestorage.app',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYpziocAYQw_bexzG-YDK7IHW_V9rwz4',
    appId: '1:522810314595:ios:8367d4523d0450106d4d56',
    messagingSenderId: '522810314595',
    projectId: 'notificationappflutter-3337c',
    storageBucket: 'notificationappflutter-3337c.firebasestorage.app',
    iosBundleId: 'com.example.notificationapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkad98agMca5bDmmCAuWJ_G9Sl34er4fI',
    appId: '1:522810314595:web:71d34f54da019d206d4d56',
    messagingSenderId: '522810314595',
    projectId: 'notificationappflutter-3337c',
    authDomain: 'notificationappflutter-3337c.firebaseapp.com',
    storageBucket: 'notificationappflutter-3337c.firebasestorage.app',
    measurementId: 'G-6BHEVV36VX',
  );
}
